version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  version: 2
  build_all:
    jobs:
      - build-test-linux-luajit
      - build-test-linux-lua53
      - build-test-osx-lua51

jobs:
  build-test-linux-luajit:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Fetch System Dependencies
          command: apt-get update -y && apt-get install -y git curl luajit libpcre3 libcurl4-openssl-dev lua-cjson
      - run:
          name: Download SDK
          command: ./download.sh
      - run:
          name: Run hello
          command: LD_LIBRARY_PATH=. luajit hello.lua

  build-test-linux-lua53:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Fetch System Dependencies
          command: apt-get update -y && apt-get install -y git curl lua5.3 lua5.3-dev libpcre3 libcurl4-openssl-dev luarocks
      - run:
          name: Install Lua Dependencies
          command: luarocks install --lua-version=5.3 lua-cjson 2.1.0-1 && luarocks install --lua-version=5.3 --server=https://luarocks.org/dev luaffi
      - run:
          name: Download SDK
          command: ./download.sh
      - run:
          name: Run hello
          command: |
            eval $(luarocks path --lua-version=5.3)
            LD_LIBRARY_PATH=. lua5.3 hello.lua

  build-test-osx-lua51:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: Fetch System Dependenciesu
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install pcre luarocks
      - run:
          name: Install Lua Dependencies
          command: luarocks install --lua-version=5.1 lua-cjson && luarocks install --lua-version=5.1 --server=https://luarocks.org/dev luaffi
      - run:
          name: Download SDK
          command: ./download.sh
      - run:
          name: Run hello
          command: |
            eval $(luarocks path --lua-version=5.1)
            LD_LIBRARY_PATH=. lua5.1 hello.lua
