version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  version: 2
  build_all:
    jobs:
      - build-test-linux
      - build-test-osx

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
      - build-test-linux
      - build-test-osx

jobs:
  build-test-linux:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - run:
          name: Fetch System Dependencies
          command: sudo apt-get update -y && sudo apt-get install -y git curl luajit libpcre3 libcurl4-openssl-dev lua-cjson luarocks
      - run:
          name: Download SDK
          command: ./download.sh
      - run:
          name: Build SDK
          command: sudo luarocks make launchdarkly-server-sdk-1.0-0.rockspec LD_DIR=. LD_INCDIR=./include
      - run:
          name: Run hello
          command: |
            LD_LIBRARY_PATH=. luajit hello.lua

  build-test-osx:
    macos:
      xcode: "11.4.0"
    steps:
      - checkout
      - run:
          name: Fetch System Dependenciesu
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install pcre lua@5.1 luarocks
      - run:
          name: Download SDK
          command: ./download.sh
      - run:
          name: Build SDK
          command: luarocks --lua-version=5.1 make launchdarkly-server-sdk-1.0-0.rockspec LD_DIR=. LD_INCDIR=./include
      - run:
          name: Run hello
          command: |
            LD_LIBRARY_PATH=. lua5.1 hello.lua
